
export interface AuthRegistrerResponse {
    username: string;
    email:    string;
    password: string;
    code:     string;
}

// Generated by https://quicktype.io

export interface Registrer {
    token:    string;
    username: string;
    email:    string;
    role:     string;
    photoUrl: string;
    created:  string;
    active:   boolean;
}
