// Generated by https://quicktype.io

export interface MoviesPopularResponse {
    page:          number;
    results:       Movie[];
    total_pages:   number;
    total_results: number;
}

export interface Movie {
    name: any;
    adult:             boolean;
    backdrop_path:     string;
    genre_ids:         number[];
    id:                number;
    original_language: string;
    original_title:    string;
    overview:          string;
    popularity:        number;
    poster_path:       string;
    release_date:      string;
    title:             string;
    video:             boolean;
    vote_average:      number;
    vote_count:        number;
}



// Generated by https://quicktype.io

export interface PlaylistResponse {
    page:          number;
    results:       Playlist[];
    total_pages:   number;
    total_results: number;
}



export interface Playlist {
    created_by:     string;
    description:    string;
    favorite_count: number;
    id:             string;
    items:          any[];
    item_count:     number;
    iso_639_1:      string;
    name:           string;
    poster_path:    null;
}
